# Generated by Django 5.2.8 on 2025-12-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FemmeMenage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=160)),
                ('telephone', models.CharField(max_length=30)),
                ('ville_zone', models.CharField(blank=True, max_length=120)),
                ('experience', models.PositiveIntegerField(default=0, help_text="Années d'expérience")),
                ('zones_couvertes', models.CharField(blank=True, help_text='Ex: Casablanca, Mohammedia, ...', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
