# Generated by Django 5.2.8 on 2025-12-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=255)),
                ('surface_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('frequence', models.CharField(blank=True, help_text='Ex: ponctuel, hebdomadaire...', max_length=80)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours'), ('TRAITEE', 'Traitée'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
